version: "3.7"
services:
  db:
    image: mariadb:10.4
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  website:
    image: richarvey/nginx-php-fpm:1.8.2
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes: 
      - .:/var/www/html

volumes:
  db-data:
